services:
  db:
    container_name: database
    image: postgres:16-alpine
    restart: 'always'
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - main

  test-db:
    container_name: database1
    image: postgres:16-alpine
    restart: 'always'
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks:
      - main

#   adminer:
#     image: adminer:latest 
#     restart: 'always'
#     ports:
#       - "8080:8080"
#     networks:
#       - main

# networks:
#   main:
#     driver: bridge



  pgadmin:
        container_name : pgadmin
        image: registry.sedrehgroup.ir/pgadmin4
        ports : 
          -  '5050:80'
        env_file:
          - .env
        networks:
          - main
networks:
  main:


